name: Nix flake check

on:
  push:
    branches:
      - master
    paths-ignore:
      - "config/**"
      - "**.md"
      - "**.txt"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "config/**"
      - "**.md"
      - "**.txt"

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Nix flake check
        run: nix flake check --all-systems --print-build-logs
